server:
  port: 3030

app:
  kafka:
    topic: payments.events
    dlq-topic: payments.events.dlq

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-samples

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: payment
    password: service

  management:
    endpoints:
      beans:
        enabled: true
      web:
        exposure:
          include: beans
  kafka:
    consumer:
      group-id: kafka-to-temporal
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        # если нужно:
        # isolation.level: read_committed
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual

  # temporal specific configs
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: me.mamre

samples:
  data:
    language: english